stage_1:
  target: stage1.RAE
  params:
    encoder_cls: 'Dinov2withNorm'
    encoder_config_path: 'facebook/dinov2-with-registers-small'
    encoder_input_size: 224
    encoder_params: {'dinov2_path': 'facebook/dinov2-with-registers-small', 'normalize': True}
    decoder_config_path: 'configs/decoder/ViTXL'
    pretrained_decoder_path: 'models/decoders/dinov2/wReg_small/ViTXL_n08/model.pt'
    noise_tau: 0.
    reshape_to_2d: True
    normalization_stat_path: 'models/stats/dinov2/wReg_small/imagenet1k/stat.pt'
